version: "3"
tasks:
  run:
    desc: Run binary
    cmds:
      - go run hook.go
  build:
    desc: Run binary
    cmds:
      - go build hook.go
  rebuild-kind:
    desc: Rebuild image and load into kind cluster
    cmds:
      - docker build . -t runner && kind load docker-image runner:latest --name kind
      - kubectl get pods -n github-runner -l app=github-runner -o name |xargs -I {} kubectl -n github-runner delete {}
  test:
    desc: Run tests
    cmds:
      - go test -race -cover ./...
  test:cover:
    desc: Run test coverage analysis
    silent: true
    cmds:
      - go test ./... -coverprofile=coverage.out
      - go tool cover -html=coverage.out
  lint:
    desc: Lint the code
    silent: true
    cmds:
      - golangci-lint run
  help:
    desc: Display this help
    silent: true
    cmds:
      - task --list
  default:
    silent: true
    cmds:
      - task: help
